import { test } from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import { EventEmitter } from 'node:events';
import { randomUUID } from 'node:crypto';
import { createRequire } from 'node:module';
import { defaults } from '../shared/types';
import { version, checkSyntax } from '../engine/syntax';
import { emptyView, viewKey } from '../shared/session';
const require = createRequire(import.meta.url);
test('main IPC creates linked runs, persists checkpoints before acknowledgement, validates references and gates rollback', async () => {
  const home = await fs.mkdtemp(path.join(os.tmpdir(),'jalo-ipc-'));
  const root=path.join(home,'sample');await fs.mkdir(root);await fs.writeFile(path.join(root,'a.txt'),'old');
  const handlers = new Map<string,Function>(), workers:any[]=[]; let window:any, userData='', fatal:any;
  const syncHandlers = new Map<string,Function>();
  let saveSelection: any = { canceled: true }, saveCalls = 0, openError = '', about: any;
  const opened: string[] = [];
  const app=new EventEmitter() as any;
  Object.assign(app,{getVersion:()=> '9.8.7',isPackaged:false,getPath:(key:string)=>key==='userData'?userData:home,setPath:(_k:string,v:string)=>userData=v,setName:()=>{},setAboutPanelOptions:(value:any)=>about=value,requestSingleInstanceLock:()=>true,whenReady:()=>Promise.resolve(),quit:()=>{}});
  class Window extends EventEmitter {
    webContents:any; constructor(){super();window=this;this.webContents={mainFrame:{},send:()=>{},setWindowOpenHandler:()=>{},on:()=>{},session:{setPermissionRequestHandler:()=>{}}};} isDestroyed(){return false} async loadURL(){} }
  const fake = {app,BrowserWindow:Window,dialog:{showOpenDialog:async()=>({canceled:false,filePaths:[root]}),showErrorBox:(_t:string,m:string)=>fatal=m},ipcMain:{handle:(n:string,h:Function)=>handlers.set(n,h)},Menu:{setApplicationMenu:()=>{},buildFromTemplate:()=>[]},safeStorage:{isEncryptionAvailable:()=>true},utilityProcess:{fork:()=>{const w=new EventEmitter() as any;w.sent=[];w.postMessage=(m:any)=>w.sent.push(m);w.kill=()=>{};workers.push(w);setImmediate(()=>w.emit('spawn'));return w;}}};
  Object.assign(fake,{shell:{openPath:async (directory:string)=>{opened.push(directory);return openError;}}});
  Object.assign(fake.ipcMain,{on:(name:string,handler:Function)=>syncHandlers.set(name,handler)});
  Object.assign(fake.dialog,{showSaveDialog:async()=>{saveCalls++;return saveSelection;}});
  const Module=require('node:module'), original=Module._load;
  Module._load=function(id:string,...args:any[]){if(id==='electron')return fake;return original.call(this,id,...args)};
  process.env.LOCAL_CODE_DEV_URL='http://127.0.0.1:5173';
  try {
    require('../electron/main.ts');
    for(let i=0;i<300 && !window && !fatal;i++)await new Promise(r=>setTimeout(r,5));
    assert.equal(fatal,undefined);assert.ok(window);
    const invoke=(name:string,...args:any[])=>handlers.get(name)!({sender:window.webContents,senderFrame:window.webContents.mainFrame},...args);
    await assert.rejects(handlers.get('app:snapshot')!({sender:{},senderFrame:{}}),/无效的调用来源/);
    await assert.rejects(handlers.get('app:export-diagnostics')!({sender:{},senderFrame:{}}),/无效的调用来源/);
    assert.equal(saveCalls,0);
    const info=await invoke('app:info');assert.equal(info.version,'9.8.7');assert.equal(about.applicationVersion,info.version);
    assert.equal(info.packaged,false);assert.equal(info.dataDirectory,userData);assert.equal(info.logDirectory,path.join(userData,'logs'));
    await invoke('app:open-data','/unexpected');assert.deepEqual(opened,[userData]);
    openError='OS refused';await assert.rejects(invoke('app:open-data'),/无法打开/);openError='';
    assert.equal(await invoke('app:export-diagnostics'),null);
    saveSelection={canceled:false,filePath:path.join(userData,'local-code.sqlite')};
    await assert.rejects(invoke('app:export-diagnostics'),/数据目录之外/);
    const project=await invoke('project:add');await invoke('settings:save',{...defaults,model:'mock'});
    const page=await invoke('files:preview',{projectId:project.id,path:'a.txt'});
    const whole=await invoke('files:reference',{projectId:project.id,path:'a.txt'});
    assert.equal(whole.scope,'file');assert.equal(whole.version,page.version);
    await assert.rejects(invoke('files:reference',{projectId:project.id,path:'../outside'}),/越出/);
    await assert.rejects(invoke('files:reference',{projectId:project.id,path:'a.txt',extra:true}));
    await assert.rejects(handlers.get('files:reference')!({sender:{},senderFrame:{}},{projectId:project.id,path:'a.txt'}),/无效的调用来源/);
    assert.equal((await invoke('files:list',{projectId:project.id,path:'.'})).entries[0].name,'a.txt');
    await assert.rejects(invoke('files:list',{projectId:project.id,path:'../'}));
    await assert.rejects(invoke('files:list',{projectId:project.id,path:'.',unexpected:true}));
    const ref={projectId:project.id,path:'a.txt',startLine:1,endLine:1,version:page.version};
    await assert.rejects(invoke('task:submit',{projectId:project.id,prompt:'x',references:[{...ref,projectId:randomUUID()}]}),/其他项目/);
    const taskId=await invoke('task:submit',{projectId:project.id,prompt:'先计划',mode:'plan',references:[ref]});
    await assert.rejects(invoke('evaluation:start'),/请先停止/);
    const snapshot=()=>invoke('app:snapshot');
    const draft={...emptyView(project.id,taskId),prompt:'尚未提交的草稿',references:[ref]};
    await invoke('session:save',draft);
    assert.equal((await invoke('session:load')).state.views[viewKey(project.id,taskId)].prompt,draft.prompt);
    await assert.rejects(invoke('session:save',{...draft,projectId:randomUUID()}),/项目不存在/);
    await assert.rejects(invoke('session:save',{...draft,taskId:randomUUID()}),/不匹配/);
    await assert.rejects(invoke('session:save',{...draft,scroll:{...draft.scroll,top:-1}}));
    const unauthorized:any={sender:{},senderFrame:{}};syncHandlers.get('session:flush')!(unauthorized,draft);assert.equal(unauthorized.returnValue.ok,false);
    const closeEvent:any={sender:window.webContents,senderFrame:window.webContents.mainFrame};
    syncHandlers.get('session:flush')!(closeEvent,{...draft,prompt:'关闭前最后输入'});assert.equal(closeEvent.returnValue.ok,true);
    assert.equal(JSON.parse(await fs.readFile(path.join(userData,'ui-session.json'),'utf8')).views[viewKey(project.id,taskId)].prompt,'关闭前最后输入');
    let task=(await snapshot()).tasks.find((t:any)=>t.id===taskId), run=task.runs[0];assert.equal(run.mode,'plan');assert.equal(run.references[0].content,'old');
    await assert.rejects(invoke('task:archive',{taskId,archived:true}),/停止或完成/);
    await assert.rejects(invoke('project:remove',project.id),/先停止任务/);
    await assert.rejects(invoke('task:rename',{taskId,title:'   '}));
    await assert.rejects(invoke('task:rename',{taskId,title:'x'.repeat(101)}));
    await assert.rejects(invoke('task:rename',{taskId:randomUUID(),title:'不存在'}),/不存在/);
    await invoke('task:rename',{taskId,title:'  新的任务名称  '});
    assert.equal((await snapshot()).tasks[0].title,'新的任务名称');
    const worker=workers.at(-1);worker.emit('message',{type:'done',runId:'other-run',status:'completed'});assert.equal((await snapshot()).tasks[0].status,'running');
    worker.emit('message',{type:'progress',runId:'other-run',progress:{phase:'generating',since:1}});
    assert.equal((await snapshot()).tasks[0].runs[0].progress.phase,'preparing');
    worker.emit('message',{type:'progress',runId:run.id,progress:{phase:'waiting_model',since:Date.now(),step:1,maxSteps:30}});
    assert.equal((await snapshot()).tasks[0].runs[0].progress.phase,'waiting_model');
    const usage={inputTokens:5000,toolTokens:1200,outputReserve:1024,safetyReserve:3277,contextLength:16384,beforeTokens:9000,compactions:1};
    worker.emit('message',{type:'context',runId:'other-run',usage});
    assert.equal((await snapshot()).tasks[0].runs[0].contextUsage,undefined);
    worker.emit('message',{type:'context',runId:run.id,usage});
    assert.deepEqual((await snapshot()).tasks[0].runs[0].contextUsage,usage);
    saveSelection={canceled:false,filePath:path.join(home,'diagnostics.json')};
    assert.equal(await invoke('app:export-diagnostics'),saveSelection.filePath);
    const report=JSON.parse(await fs.readFile(saveSelection.filePath,'utf8'));
    assert.equal(report.app.version,'9.8.7');assert.equal(report.tasks[0].status,'running');
    assert.ok(report.logs.entries.some((entry:any)=>entry.event==='task_phase'&&entry.phase==='waiting_model'));
    assert.ok(report.logs.entries.some((entry:any)=>entry.event==='ipc_error'));
    assert.ok(!JSON.stringify(report).includes('新的任务名称'));assert.ok(!JSON.stringify(report).includes(root));
    worker.emit('message',{type:'approval',runId:run.id,approval:{id:randomUUID(),command:'node --version',cwd:root,timeout:1}});
    assert.equal((await snapshot()).tasks[0].runs[0].progress.phase,'approval');
    worker.emit('message',{type:'approval-resolved',runId:run.id});
    assert.equal((await snapshot()).tasks[0].runs[0].progress.phase,'tool');
    worker.emit('message',{type:'event',runId:run.id,event:{id:randomUUID(),runId:run.id,at:Date.now(),kind:'message',role:'assistant',text:'读取 a.txt，再将 old 改为 new，重新读取验收。'}});
    worker.emit('message',{type:'done',runId:run.id,status:'completed',evidence:{successfulTools:['read_file'],changedFiles:[]}});
    assert.ok((await snapshot()).tasks[0].runs[0].progress.endedAt);
    await invoke('task:archive',{taskId,archived:true});
    const archived=(await snapshot()).tasks[0];assert.ok(archived.archivedAt);assert.equal(archived.runs[0].status,'completed');
    await assert.rejects(invoke('task:submit',{projectId:project.id,taskId,prompt:'不应执行'}),/先恢复/);
    await invoke('task:archive',{taskId,archived:false});assert.equal((await snapshot()).tasks[0].archivedAt,undefined);
    await invoke('task:submit',{projectId:project.id,taskId,prompt:'执行计划',mode:'execute',planRunId:run.id});
    task=(await snapshot()).tasks[0];const second=task.runs.at(-1);assert.notEqual(second.id,run.id);assert.equal(second.planRunId,run.id);
    const w=workers.at(-1), change={id:randomUUID(),runId:second.id,path:'a.txt',before:'old',after:'new',beforeVersion:version('old'),afterVersion:version('new'),check:checkSyntax('a.txt','new'),state:'prepared',patch:'-old\n+new'};
    w.emit('message',{type:'checkpoint',runId:second.id,checkpoint:change});
    assert.ok(w.sent.some((m:any)=>m.type==='checkpoint-ack'&&m.id===change.id));
    const SQL=await require('sql.js')();const db=new SQL.Database(await fs.readFile(path.join(userData,'local-code.sqlite')));assert.equal(db.exec('SELECT count(*) FROM checkpoints')[0].values[0][0],1);db.close();
    await fs.writeFile(path.join(root,'a.txt'),'new');w.emit('message',{type:'change',runId:second.id,change:{path:'a.txt',before:'old',after:'new',patch:change.patch},checkpoint:{...change,state:'written'}});
    await assert.rejects(invoke('rollback:preview',{taskId,runId:second.id,path:'a.txt'}),/运行中或排队/);
    w.emit('message',{type:'done',runId:second.id,status:'completed',evidence:{successfulTools:['write_file'],changedFiles:['a.txt']}});
    const preview=await invoke('rollback:preview',{taskId,runId:second.id,path:'a.txt'});assert.match(preview.patch,/-new/);
    await fs.writeFile(path.join(root,'a.txt'),'manual');await assert.rejects(invoke('rollback:confirm',preview.token),/冲突/);assert.equal(await fs.readFile(path.join(root,'a.txt'),'utf8'),'manual');
    await fs.writeFile(path.join(root,'a.txt'),'new');const preview2=await invoke('rollback:preview',{taskId,runId:second.id,path:'a.txt'});await invoke('rollback:confirm',preview2.token);
    assert.equal(await fs.readFile(path.join(root,'a.txt'),'utf8'),'old');task=(await snapshot()).tasks[0];assert.equal(task.runs.at(-1).changes[0].state,'reverted');assert.equal(task.changes.length,0);assert.ok(task.messages.at(-1).content.includes('重新读取'));
    await assert.rejects(invoke('task:submit',{projectId:project.id,taskId,prompt:'review',mode:'review'}),/选择已有核验记录/);
    await invoke('task:submit',{projectId:project.id,taskId,prompt:'review',mode:'review',reviewRunId:second.id});assert.equal((await snapshot()).tasks[0].runs.at(-1).reviewRunId,second.id);
    const lastRun=(await snapshot()).tasks[0].currentRunId;
    workers.at(-1).emit('message',{type:'done',runId:lastRun,status:'completed'});
    const beforeRemoval=(await snapshot()).tasks;
    await invoke('project:remove',project.id);
    assert.equal((await snapshot()).projects.length,0);assert.deepEqual((await snapshot()).tasks,beforeRemoval);
    assert.equal(await fs.readFile(path.join(root,'a.txt'),'utf8'),'old');
    await assert.rejects(invoke('task:submit',{projectId:project.id,prompt:'已移除项目'}),/项目/);
    const restored=await invoke('project:add');assert.equal(restored.id,project.id);assert.equal(restored.removedAt,undefined);
    assert.deepEqual((await snapshot()).tasks,beforeRemoval);assert.equal((await snapshot()).projects.length,1);
    const activeTask=(await snapshot()).tasks.find((t:any)=>['running','waiting','queued'].includes(t.status));
    if(activeTask)workers.at(-1).emit('message',{type:'done',runId:activeTask.currentRunId,status:'completed'});
    const evaluationId=await invoke('evaluation:start'), evaluationWorker=workers.at(-1);
    await new Promise(r=>setImmediate(r));const start=evaluationWorker.sent.find((m:any)=>m.type==='evaluate');assert.ok(start);
    assert.notEqual(start.home,root);assert.equal(start.settings.model,'mock');
    await assert.rejects(invoke('settings:save',{...defaults,model:'other'}),/实测/);
    await assert.rejects(invoke('models:unload','mock'),/实测/);
    await assert.rejects(invoke('task:submit',{projectId:project.id,prompt:'cannot run'}),/实测/);
    await assert.rejects(invoke('evaluation:start'),/实测/);
    await invoke('evaluation:stop',evaluationId);assert.equal(evaluationWorker.sent.at(-1).type,'cancel');
    evaluationWorker.emit('message',{type:'evaluation-update',report:{...start.report,status:'cancelled'}});evaluationWorker.emit('exit',0);
    assert.equal((await snapshot()).evaluations[0].status,'cancelled');await assert.rejects(fs.access(start.home));
    await invoke('settings:save',{...defaults,model:'mock'});
  } finally { Module._load=original;app.emit('before-quit');await fs.rm(home,{recursive:true,force:true}); }
});
