import { test } from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import { EventEmitter } from 'node:events';
import { randomUUID } from 'node:crypto';
import { createRequire } from 'node:module';
import { DatabaseSync } from 'node:sqlite';
import { defaults } from '../shared/types';
import { version, checkSyntax } from '../engine/syntax';
import { emptyView, viewKey } from '../shared/session';
import { Store, taskSaveDelay } from '../electron/store';
import { streamDelay } from '../electron/ipc-updates';
import { MessagePatchSender } from '../shared/worker-wire';
const require = createRequire(import.meta.url);
test('main IPC creates linked runs, persists checkpoints before acknowledgement, validates references and gates rollback', async () => {
  const home = await fs.mkdtemp(path.join(os.tmpdir(),'jalo-ipc-'));
  const root=path.join(home,'sample');await fs.mkdir(root);await fs.writeFile(path.join(root,'a.txt'),'old');
  const handlers = new Map<string,Function>(), workers:any[]=[]; let window:any, userData='', fatal:any;
  const syncHandlers = new Map<string,Function>();
  let saveSelection: any = { canceled: true }, saveCalls = 0, openError = '', about: any;
  const opened: string[] = [], externalLinks: string[] = [], copied: string[] = [], deliveries: { channel: string; value: any }[] = [];
  const originalFlush = Store.prototype.flush;
  const originalTask = Store.prototype.task, originalTasks = Store.prototype.tasks, originalDetail = Store.prototype.detail;
  let bodyReads = 0, detailReads = 0;
  Store.prototype.tasks = () => { throw new Error('main must not load all task history'); };
  Store.prototype.task = function (id) { bodyReads++; return originalTask.call(this, id); };
  Store.prototype.detail = function (id, revision) { detailReads++; return originalDetail.call(this, id, revision); };
  let flushes = 0, failWrites = false;
  Store.prototype.flush = function () {
    flushes++;
    const db = (this as any).db, originalExec = db.exec;
    if (failWrites) db.exec = function (sql: string) { if (/^COMMIT\b/.test(sql)) throw new Error('模拟磁盘写入失败'); return originalExec.call(this, sql); };
    try { return originalFlush.call(this); }
    finally { db.exec = originalExec; }
  };
  const app=new EventEmitter() as any;
  Object.assign(app,{getVersion:()=> '9.8.7',isPackaged:false,getPath:(key:string)=>key==='userData'?userData:home,setPath:(_k:string,v:string)=>userData=v,setName:()=>{},setAboutPanelOptions:(value:any)=>about=value,requestSingleInstanceLock:()=>true,whenReady:()=>Promise.resolve(),quit:()=>{}});
  class Window extends EventEmitter {
    webContents:any; constructor(){super();window=this;this.webContents={mainFrame:{},send:(channel:string,value:any)=>deliveries.push({channel,value:structuredClone(value)}),setWindowOpenHandler:()=>{},on:()=>{},session:{setPermissionRequestHandler:()=>{}}};} isDestroyed(){return false} async loadURL(){} }
  const fake = {app,BrowserWindow:Window,dialog:{showOpenDialog:async()=>({canceled:false,filePaths:[root]}),showErrorBox:(_t:string,m:string)=>fatal=m},ipcMain:{handle:(n:string,h:Function)=>handlers.set(n,h)},Menu:{setApplicationMenu:()=>{},buildFromTemplate:()=>[]},safeStorage:{isEncryptionAvailable:()=>true},utilityProcess:{fork:()=>{const w=new EventEmitter() as any;w.sent=[];w.postMessage=(m:any)=>w.sent.push(m);w.kill=()=>{w.killed=true;};workers.push(w);setImmediate(()=>w.emit('spawn'));return w;}}};
  Object.assign(fake,{shell:{openPath:async (directory:string)=>{opened.push(directory);return openError;},openExternal:async (url:string)=>{externalLinks.push(url);}},clipboard:{writeText:(text:string)=>copied.push(text)}});
  Object.assign(fake.ipcMain,{on:(name:string,handler:Function)=>syncHandlers.set(name,handler)});
  Object.assign(fake.dialog,{showSaveDialog:async()=>{saveCalls++;return saveSelection;}});
  const Module=require('node:module'), original=Module._load;
  Module._load=function(id:string,...args:any[]){if(id==='electron')return fake;return original.call(this,id,...args)};
  process.env.LOCAL_CODE_DEV_URL='http://127.0.0.1:5173';
  try {
    require('../electron/main.ts');
    for(let i=0;i<300 && !window && !fatal;i++)await new Promise(r=>setTimeout(r,5));
    assert.equal(fatal,undefined);assert.ok(window);
    const invoke=(name:string,...args:any[])=>handlers.get(name)!({sender:window.webContents,senderFrame:window.webContents.mainFrame},...args);
    await assert.rejects(handlers.get('app:snapshot')!({sender:{},senderFrame:{}}),/无效的调用来源/);
    await assert.rejects(handlers.get('app:export-diagnostics')!({sender:{},senderFrame:{}}),/无效的调用来源/);
    assert.equal(saveCalls,0);
    const info=await invoke('app:info');assert.equal(info.version,'9.8.7');assert.equal(about.applicationVersion,info.version);
    assert.equal(info.packaged,false);assert.equal(info.dataDirectory,userData);assert.equal(info.logDirectory,path.join(userData,'logs'));
    await invoke('app:open-data','/unexpected');assert.deepEqual(opened,[userData]);
    openError='OS refused';await assert.rejects(invoke('app:open-data'),/无法打开/);openError='';
    await invoke('app:open-link','https://example.com/docs');assert.deepEqual(externalLinks,['https://example.com/docs']);
    for(const url of ['javascript:alert(1)','file:///etc/passwd','vscode://open','//example.com','https://user:password@example.com','https://example.com\n'])await assert.rejects(invoke('app:open-link',url),/HTTP\/HTTPS/);
    await assert.rejects(invoke('app:open-link','https://example.com/'+'x'.repeat(8192)));
    await assert.rejects(handlers.get('app:open-link')!({sender:{},senderFrame:{}},'https://example.com'),/无效的调用来源/);
    assert.equal(externalLinks.length,1);
    const code='  echo "<data>"\n';await invoke('app:copy-text',code);assert.deepEqual(copied,[code]);
    await assert.rejects(invoke('app:copy-text',{text:code}));await assert.rejects(invoke('app:copy-text','x'.repeat(1000001)));
    await assert.rejects(handlers.get('app:copy-text')!({sender:{},senderFrame:{}},code),/无效的调用来源/);assert.equal(copied.length,1);
    assert.equal(await invoke('app:export-diagnostics'),null);
    saveSelection={canceled:false,filePath:path.join(userData,'local-code.sqlite')};
    await assert.rejects(invoke('app:export-diagnostics'),/数据目录之外/);
    const project=await invoke('project:add');await invoke('settings:save',{...defaults,model:'mock'});
    const page=await invoke('files:preview',{projectId:project.id,path:'a.txt'});
    const whole=await invoke('files:reference',{projectId:project.id,path:'a.txt'});
    assert.equal(whole.scope,'file');assert.equal(whole.version,page.version);
    await assert.rejects(invoke('files:reference',{projectId:project.id,path:'../outside'}),/越出/);
    await assert.rejects(invoke('files:reference',{projectId:project.id,path:'a.txt',extra:true}));
    await assert.rejects(handlers.get('files:reference')!({sender:{},senderFrame:{}},{projectId:project.id,path:'a.txt'}),/无效的调用来源/);
    assert.equal((await invoke('files:list',{projectId:project.id,path:'.'})).entries[0].name,'a.txt');
    await assert.rejects(invoke('files:list',{projectId:project.id,path:'../'}));
    await assert.rejects(invoke('files:list',{projectId:project.id,path:'.',unexpected:true}));
    const ref={projectId:project.id,path:'a.txt',startLine:1,endLine:1,version:page.version};
    await assert.rejects(invoke('task:submit',{projectId:project.id,prompt:'x',references:[{...ref,projectId:randomUUID()}]}),/其他项目/);
    const taskId=await invoke('task:submit',{projectId:project.id,prompt:'先计划',mode:'plan',references:[ref]});
    await assert.rejects(invoke('evaluation:start'),/请先停止/);
    const snapshot=async()=>{ const summary=await invoke('app:snapshot'); return {...summary,tasks:await Promise.all(summary.tasks.map((task:any)=>invoke('task:detail',task.id)))}; };
    const catalog=await invoke('app:snapshot');
    assert.ok(!('messages' in catalog.tasks[0]));assert.ok(!('events' in catalog.tasks[0]));assert.ok(!('runs' in catalog.tasks[0]));assert.ok(!('changes' in catalog.tasks[0]));
    await assert.rejects(invoke('task:detail',randomUUID()),/任务不存在/);
    await assert.rejects(handlers.get('task:detail')!({sender:{},senderFrame:{}},taskId),/无效的调用来源/);
    const draft={...emptyView(project.id,taskId),prompt:'尚未提交的草稿',references:[ref]};
    await invoke('session:save',draft);
    assert.equal((await invoke('session:load')).state.views[viewKey(project.id,taskId)].prompt,draft.prompt);
    await assert.rejects(invoke('session:save',{...draft,projectId:randomUUID()}),/项目不存在/);
    await assert.rejects(invoke('session:save',{...draft,taskId:randomUUID()}),/不匹配/);
    await assert.rejects(invoke('session:save',{...draft,scroll:{...draft.scroll,top:-1}}));
    const unauthorized:any={sender:{},senderFrame:{}};syncHandlers.get('session:flush')!(unauthorized,draft);assert.equal(unauthorized.returnValue.ok,false);
    const closeEvent:any={sender:window.webContents,senderFrame:window.webContents.mainFrame};
    syncHandlers.get('session:flush')!(closeEvent,{...draft,prompt:'关闭前最后输入'});assert.equal(closeEvent.returnValue.ok,true);
    assert.equal(JSON.parse(await fs.readFile(path.join(userData,'ui-session.json'),'utf8')).views[viewKey(project.id,taskId)].prompt,'关闭前最后输入');
    let task=(await snapshot()).tasks.find((t:any)=>t.id===taskId), run=task.runs[0];assert.equal(run.mode,'plan');assert.ok(!('content' in run.references[0]));assert.ok(!('messages' in task));
    await assert.rejects(invoke('task:archive',{taskId,archived:true}),/停止或完成/);
    await assert.rejects(invoke('project:remove',project.id),/先停止任务/);
    await assert.rejects(invoke('task:rename',{taskId,title:'   '}));
    await assert.rejects(invoke('task:rename',{taskId,title:'x'.repeat(101)}));
    await assert.rejects(invoke('task:rename',{taskId:randomUUID(),title:'不存在'}),/不存在/);
    await invoke('task:rename',{taskId,title:'  新的任务名称  '});
    assert.equal((await snapshot()).tasks[0].title,'新的任务名称');
    const worker=workers.at(-1);worker.emit('message',{type:'done',runId:'other-run',status:'completed'});assert.equal((await snapshot()).tasks[0].status,'running');
    const firstInput=worker.sent.find((m:any)=>m.type==='start').input;
    assert.ok(!('content' in firstInput.run.references[0]));
    const planMessages=[{role:'system' as const,content:'plan rules'},...firstInput.messages];
    const planSender=new MessagePatchSender(firstInput.messages), setupPatch=planSender.update(planMessages)!;
    worker.emit('message',{...setupPatch,runId:'other-run'});
    worker.emit('message',{...setupPatch,runId:run.id});worker.emit('message',{...setupPatch,runId:run.id});
    worker.emit('message',{type:'progress',runId:'other-run',progress:{phase:'generating',since:1}});
    assert.equal((await snapshot()).tasks[0].runs[0].progress.phase,'preparing');
    worker.emit('message',{type:'progress',runId:run.id,progress:{phase:'waiting_model',since:Date.now(),step:1,maxSteps:30}});
    assert.equal((await snapshot()).tasks[0].runs[0].progress.phase,'waiting_model');
    const beforeDeltas=deliveries.filter(delivery=>delivery.channel==='task:delta').length;
    for(let i=0;i<1000;i++)worker.emit('message',{type:'delta',runId:run.id,text:'流'});
    assert.equal(deliveries.filter(delivery=>delivery.channel==='task:delta').length,beforeDeltas);
    const activeStream=(await invoke('task:detail',taskId)).stream;assert.equal(activeStream.text,'流'.repeat(1000));
    await new Promise(resolve=>setTimeout(resolve,streamDelay+10));
    const streamed=deliveries.filter(delivery=>delivery.channel==='task:delta');assert.equal(streamed.length,beforeDeltas+1);
    assert.equal(streamed.at(-1)!.value.text,'流'.repeat(1000));assert.equal(streamed.at(-1)!.value.runId,run.id);
    const usage={inputTokens:5000,toolTokens:1200,outputReserve:1024,safetyReserve:3277,contextLength:16384,beforeTokens:9000,compactions:1};
    worker.emit('message',{type:'context',runId:'other-run',usage});
    assert.equal((await snapshot()).tasks[0].runs[0].contextUsage,undefined);
    worker.emit('message',{type:'context',runId:run.id,usage});
    assert.deepEqual((await snapshot()).tasks[0].runs[0].contextUsage,usage);
    saveSelection={canceled:false,filePath:path.join(home,'diagnostics.json')};
    assert.equal(await invoke('app:export-diagnostics'),saveSelection.filePath);
    const report=JSON.parse(await fs.readFile(saveSelection.filePath,'utf8'));
    assert.equal(report.app.version,'9.8.7');assert.equal(report.tasks[0].status,'running');
    assert.ok(report.logs.entries.some((entry:any)=>entry.event==='task_phase'&&entry.phase==='waiting_model'));
    assert.ok(report.logs.entries.some((entry:any)=>entry.event==='ipc_error'));
    assert.ok(!JSON.stringify(report).includes('新的任务名称'));assert.ok(!JSON.stringify(report).includes(root));
    worker.emit('message',{type:'approval',runId:run.id,approval:{id:randomUUID(),command:'node --version',cwd:root,timeout:1}});
    assert.equal((await snapshot()).tasks[0].runs[0].progress.phase,'approval');
    worker.emit('message',{type:'approval-resolved',runId:run.id});
    assert.equal((await snapshot()).tasks[0].runs[0].progress.phase,'tool');
    const savedPlan='开头的完整约束\n'+'计划内容。'.repeat(3000)+'\n读取 a.txt，再将 old 改为 new，重新读取验收。';
    const beforeEvents = flushes;
    const beforeUpdates=deliveries.filter(delivery=>delivery.channel==='app:update').length;
    planMessages.push({role:'assistant',content:savedPlan});
    worker.emit('message',{...planSender.update(planMessages),runId:run.id});
    worker.emit('message',{type:'event',runId:run.id,event:{id:randomUUID(),runId:run.id,at:Date.now(),kind:'message',role:'assistant',text:'临时思路，不应成为执行计划'}});
    for(let i=0;i<605;i++)worker.emit('message',{type:'event',runId:run.id,event:{id:randomUUID(),runId:run.id,at:Date.now(),kind:'notice',text:`历史记录 ${i}`}});
    assert.equal(flushes,beforeEvents);
    assert.equal(deliveries.filter(delivery=>delivery.channel==='app:update').length,beforeUpdates);
    worker.emit('message',{type:'done',runId:run.id,status:'completed',result:savedPlan,evidence:{successfulTools:['read_file'],changedFiles:[]}});
    assert.equal(flushes,beforeEvents+1);
    assert.equal(deliveries.filter(delivery=>delivery.channel==='app:update').length,beforeUpdates+1);
    const update=deliveries.filter(delivery=>delivery.channel==='app:update').at(-1)!.value;
    assert.deepEqual(update.tasks.map((task:any)=>task.id),[taskId]);assert.ok(!('settings' in update));
    assert.ok(!JSON.stringify(update).includes(savedPlan));
    const readsBeforeHistory = bodyReads, detailsBeforeHistory = detailReads;
    const historyTask=(await snapshot()).tasks[0];assert.equal(historyTask.events.length,100);assert.ok(historyTask.eventCount>600);assert.equal(historyTask.runs[0].hasPlan,true);assert.ok(!('planText' in historyTask.runs[0]));assert.equal(await invoke('runs:plan',{taskId,runId:run.id}),savedPlan);
    assert.ok(detailReads > detailsBeforeHistory, 'completed tasks must be released and details read from the catalog');
    await assert.rejects(invoke('task:events',{taskId:randomUUID()}),/任务不存在/);
    await assert.rejects(invoke('task:events',{taskId,before:'wrong-cursor'}),/游标不存在/);
    for(const direction of ['after','around'])await assert.rejects(invoke('task:events',{taskId,[direction]:'wrong-cursor'}),/游标不存在/);
    for(const cursors of [{before:'one',after:'two'},{before:'one',around:'two'},{after:'one',around:'two'}])await assert.rejects(invoke('task:events',{taskId,...cursors}),/一个方向/);
    for(const cursors of [{after:''},{around:'x'.repeat(201)},{before:5}])await assert.rejects(invoke('task:events',{taskId,...cursors}));
    await assert.rejects(invoke('task:events',{taskId,extra:true}));
    await assert.rejects(handlers.get('task:events')!({sender:{},senderFrame:{}},{taskId}),/无效的调用来源/);
    let historyPage=await invoke('task:events',{taskId}), loadedEvents=historyPage.events;
    while(historyPage.hasMore){historyPage=await invoke('task:events',{taskId,before:historyPage.events[0].id});loadedEvents=[...historyPage.events,...loadedEvents];}
    assert.equal(loadedEvents.length,historyTask.eventCount);assert.equal(loadedEvents[0].role,'user');
    const directPage=await invoke('task:events',{taskId,around:loadedEvents[250].id});
    assert.equal(directPage.start,200);assert.deepEqual(directPage.events,loadedEvents.slice(200,300));
    const nextPage=await invoke('task:events',{taskId,after:directPage.events.at(-1).id});
    assert.equal(nextPage.start,300);assert.deepEqual(nextPage.events,loadedEvents.slice(300,400));
    assert.ok((await snapshot()).tasks[0].runs[0].progress.endedAt);
    await invoke('task:archive',{taskId,archived:true});
    const archived=(await snapshot()).tasks[0];assert.ok(archived.archivedAt);assert.equal(archived.runs[0].status,'completed');
    await invoke('task:rename',{taskId,title:'新的任务名称'});
    assert.deepEqual(await invoke('tasks:search',{projectId:project.id,archived:true,query:'先计划'}),[taskId]);
    assert.equal(bodyReads, readsBeforeHistory, 'paging, plans, search, rename and archive must not hydrate full history');
    await assert.rejects(invoke('task:submit',{projectId:project.id,taskId,prompt:'不应执行'}),/先恢复/);
    await invoke('task:archive',{taskId,archived:false});assert.equal((await snapshot()).tasks[0].archivedAt,undefined);
    const readsBeforeResume = bodyReads;
    await invoke('task:submit',{projectId:project.id,taskId,prompt:'执行计划',model:'plan-model',mode:'execute',planRunId:run.id});
    assert.equal(bodyReads, readsBeforeResume + 1, 'resuming hydrates exactly the selected task');
    task=(await snapshot()).tasks[0];const second=task.runs.at(-1);assert.notEqual(second.id,run.id);assert.equal(second.planRunId,run.id);
    await new Promise(r=>setImmediate(r));
    const startMessage=workers.at(-1).sent.find((m:any)=>m.type==='start');
    assert.equal(startMessage.input.model,'plan-model');assert.equal(startMessage.settings.model,'plan-model');
    assert.equal(second.model,'plan-model');assert.equal(task.runs[0].model,'mock');
    assert.equal((await invoke('app:snapshot')).settings.model,'mock');
    assert.ok(startMessage.input.messages.at(-1).content.includes(savedPlan));assert.ok(!startMessage.input.messages.at(-1).content.includes('临时思路'));
    assert.equal(startMessage.input.messages.length,1);assert.ok(!('task' in startMessage));
    assert.ok(!('runs' in startMessage.input));assert.ok(!('events' in startMessage.input));
    const linkedSender=new MessagePatchSender(startMessage.input.messages);
    const linkedMessages=[{role:'system' as const,content:'execute rules'},...startMessage.input.messages];
    workers.at(-1).emit('message',{...linkedSender.update(linkedMessages),runId:second.id});
    linkedMessages.push({role:'assistant',content:'linked round context'});
    workers.at(-1).emit('message',{...linkedSender.update(linkedMessages),runId:second.id});
    const w=workers.at(-1), change={id:randomUUID(),runId:second.id,path:'a.txt',before:'old',after:'new',beforeVersion:version('old'),afterVersion:version('new'),check:checkSyntax('a.txt','new'),state:'prepared',patch:'-old\n+new'};
    w.emit('message',{type:'checkpoint',runId:second.id,checkpoint:change});
    assert.ok(w.sent.some((m:any)=>m.type==='checkpoint-ack'&&m.id===change.id));
    const db=new DatabaseSync(path.join(userData,'local-code.sqlite'),{readOnly:true});assert.equal(db.prepare('SELECT count(*) AS count FROM checkpoints').get()!.count,1);
    const stored=JSON.parse(String(db.prepare('SELECT data FROM tasks WHERE id=?').get(taskId)!.data));
    assert.deepEqual(stored.messages,[...planMessages,...linkedMessages]);db.close();
    await fs.writeFile(path.join(root,'a.txt'),'new');w.emit('message',{type:'change',runId:second.id,change:{path:'a.txt',before:'old',after:'new',patch:change.patch},checkpoint:{...change,state:'written'}});
    const patch=await invoke('changes:patch',{taskId,runId:second.id,path:'a.txt'});assert.equal(patch.patch,change.patch);
    const detail=await invoke('task:detail',taskId);assert.equal(detail.runs.at(-1).changes[0].patchVersion,patch.version);
    for(const key of ['before','after','patch'])assert.ok(!(key in detail.runs.at(-1).changes[0]));
    await assert.rejects(invoke('changes:patch',{taskId,runId:run.id,path:'a.txt'}),/修改记录不存在/);
    await assert.rejects(invoke('changes:patch',{taskId,runId:second.id,path:'a.txt',extra:true}));
    await assert.rejects(invoke('runs:plan',{taskId,runId:second.id}),/计划缺少/);
    await assert.rejects(invoke('tasks:search',{projectId:project.id,archived:false,query:'计划',extra:true}));
    assert.deepEqual(await invoke('tasks:search',{projectId:project.id,archived:false,query:'先计划'}),[taskId]);
    await assert.rejects(invoke('rollback:preview',{taskId,runId:second.id,path:'a.txt'}),/运行中或排队/);
    w.emit('message',{type:'done',runId:second.id,status:'completed',evidence:{successfulTools:['write_file'],changedFiles:['a.txt']}});
    const preview=await invoke('rollback:preview',{taskId,runId:second.id,path:'a.txt'});assert.match(preview.patch,/-new/);
    await fs.writeFile(path.join(root,'a.txt'),'manual');await assert.rejects(invoke('rollback:confirm',preview.token),/冲突/);assert.equal(await fs.readFile(path.join(root,'a.txt'),'utf8'),'manual');
    await fs.writeFile(path.join(root,'a.txt'),'new');const preview2=await invoke('rollback:preview',{taskId,runId:second.id,path:'a.txt'});await invoke('rollback:confirm',preview2.token);
    assert.equal(await fs.readFile(path.join(root,'a.txt'),'utf8'),'old');task=(await snapshot()).tasks[0];assert.equal(task.runs.at(-1).changes[0].state,'reverted');assert.equal(task.changes.length,0);assert.ok(task.events.at(-1).text.includes('重新读取'));
    await assert.rejects(invoke('task:submit',{projectId:project.id,taskId,prompt:'review',mode:'review'}),/选择已有核验记录/);
    await invoke('task:submit',{projectId:project.id,taskId,prompt:'review',model:'review-model',mode:'review',reviewRunId:second.id});assert.equal((await snapshot()).tasks[0].runs.at(-1).reviewRunId,second.id);
    assert.equal((await snapshot()).tasks[0].runs.at(-1).model,'review-model');
    const lastRun=(await snapshot()).tasks[0].currentRunId;
    workers.at(-1).emit('message',{type:'done',runId:lastRun,status:'completed'});
    const beforeRemoval=(await snapshot()).tasks;
    await invoke('project:remove',project.id);
    assert.equal((await snapshot()).projects.length,0);assert.deepEqual((await snapshot()).tasks,beforeRemoval);
    assert.equal(await fs.readFile(path.join(root,'a.txt'),'utf8'),'old');
    await assert.rejects(invoke('task:submit',{projectId:project.id,prompt:'已移除项目'}),/项目/);
    const restored=await invoke('project:add');assert.equal(restored.id,project.id);assert.equal(restored.removedAt,undefined);
    assert.deepEqual((await snapshot()).tasks,beforeRemoval);assert.equal((await snapshot()).projects.length,1);
    const activeTask=(await snapshot()).tasks.find((t:any)=>['running','waiting','queued'].includes(t.status));
    if(activeTask)workers.at(-1).emit('message',{type:'done',runId:activeTask.currentRunId,status:'completed'});
    const evaluationId=await invoke('evaluation:start'), evaluationWorker=workers.at(-1);
    await new Promise(r=>setImmediate(r));const start=evaluationWorker.sent.find((m:any)=>m.type==='evaluate');assert.ok(start);
    assert.notEqual(start.home,root);assert.equal(start.settings.model,'mock');
    await assert.rejects(invoke('settings:save',{...defaults,model:'other'}),/实测/);
    await assert.rejects(invoke('models:unload','mock'),/实测/);
    await assert.rejects(invoke('task:submit',{projectId:project.id,prompt:'cannot run'}),/实测/);
    await assert.rejects(invoke('evaluation:start'),/实测/);
    await invoke('evaluation:stop',evaluationId);assert.equal(evaluationWorker.sent.at(-1).type,'cancel');
    evaluationWorker.emit('message',{type:'evaluation-update',report:{...start.report,status:'cancelled'}});evaluationWorker.emit('exit',0);
    assert.equal((await snapshot()).evaluations[0].status,'cancelled');await assert.rejects(fs.access(start.home));
    await invoke('settings:save',{...defaults,model:'mock'});
    // Saving failures must stop a worker before any successful checkpoint acknowledgement.
    const failedId=await invoke('task:submit',{projectId:project.id,prompt:'checkpoint failure',mode:'execute'});
    const failedTask=(await snapshot()).tasks.find((t:any)=>t.id===failedId), failedWorker=workers.at(-1);
    const failedCheckpoint={...change,id:randomUUID(),runId:failedTask.currentRunId};
    failWrites=true;failedWorker.emit('message',{type:'checkpoint',runId:failedTask.currentRunId,checkpoint:failedCheckpoint});
    assert.ok(failedWorker.killed);
    assert.ok(!failedWorker.sent.some((m:any)=>m.type==='checkpoint-ack'&&!m.error));
    assert.equal((await snapshot()).tasks.find((t:any)=>t.id===failedId).status,'failed');
    assert.equal(await fs.readFile(path.join(root,'a.txt'),'utf8'),'old');
    failWrites=false;
    await invoke('task:submit',{projectId:project.id,taskId:failedId,prompt:'手动检查后继续',mode:'execute'});
    const resumed=(await snapshot()).tasks.find((t:any)=>t.id===failedId);
    workers.at(-1).emit('message',{type:'done',runId:resumed.currentRunId,status:'completed'});
    // A delayed failure also stops execution, and must not start the queued task.
    const delayedId=await invoke('task:submit',{projectId:project.id,prompt:'deferred failure'});
    const delayedTask=(await snapshot()).tasks.find((t:any)=>t.id===delayedId), delayedWorker=workers.at(-1);
    const queuedId=await invoke('task:submit',{projectId:project.id,prompt:'stay queued'}), workerCount=workers.length;
    failWrites=true;
    delayedWorker.emit('message',{type:'progress',runId:delayedTask.currentRunId,progress:{phase:'generating',since:Date.now()}});
    await new Promise(r=>setTimeout(r,taskSaveDelay+30));
    assert.ok(delayedWorker.killed);assert.equal(workers.length,workerCount);
    assert.match((await snapshot()).tasks.find((t:any)=>t.id===delayedId).error,/保存失败/);
    assert.equal((await snapshot()).tasks.find((t:any)=>t.id===queuedId).status,'queued');
    failWrites=false;await invoke('task:stop',queuedId);
    // A user's approval must reach durable storage before the worker receives it.
    const approvalTaskId=await invoke('task:submit',{projectId:project.id,prompt:'approval persistence'});
    const approvalTask=(await snapshot()).tasks.find((t:any)=>t.id===approvalTaskId), approvalWorker=workers.at(-1), approvalId=randomUUID();
    approvalWorker.emit('message',{type:'approval',runId:approvalTask.currentRunId,approval:{id:approvalId,command:'node --version',cwd:root,timeout:1}});
    failWrites=true;
    await assert.rejects(invoke('task:approve',{taskId:approvalTaskId,approvalId,allow:true}),/磁盘写入失败/);
    assert.ok(approvalWorker.killed);assert.ok(!approvalWorker.sent.some((m:any)=>m.type==='approve'));
    assert.equal((await snapshot()).tasks.find((t:any)=>t.id===approvalTaskId).status,'failed');
    failWrites=false;
    await invoke('task:submit',{projectId:project.id,taskId:approvalTaskId,prompt:'检查后手动继续'});
    const last=(await snapshot()).tasks.find((t:any)=>t.id===approvalTaskId);
    workers.at(-1).emit('message',{type:'done',runId:last.currentRunId,status:'completed'});
    // A synchronous metadata save must notify the pending worker, too.
    const renameId=await invoke('task:submit',{projectId:project.id,prompt:'rename during deferred save'});
    const renameTask=(await snapshot()).tasks.find((t:any)=>t.id===renameId), renameWorker=workers.at(-1);
    const waitingId=await invoke('task:submit',{projectId:project.id,prompt:'wait for storage recovery'}), beforeFailure=workers.length;
    renameWorker.emit('message',{type:'event',runId:renameTask.currentRunId,event:{id:randomUUID(),at:Date.now(),kind:'notice',text:'pending history'}});
    failWrites=true;
    try {
      await assert.rejects(invoke('task:rename',{taskId:renameId,title:'renamed during save'}),/模拟磁盘写入失败/);
      assert.ok(renameWorker.killed);
      const stopped=(await snapshot()).tasks.find((t:any)=>t.id===renameId);
      assert.equal(stopped.status,'failed'); assert.match(stopped.error,/保存失败/);
      assert.equal((await snapshot()).activeId,undefined);
      await new Promise(r=>setTimeout(r,taskSaveDelay+30));
      assert.equal(workers.length,beforeFailure);
      assert.equal((await snapshot()).tasks.find((t:any)=>t.id===waitingId).status,'queued');
    } finally { failWrites=false; }
    await invoke('task:stop',waitingId);
    await invoke('task:submit',{projectId:project.id,taskId:renameId,prompt:'storage recovered; continue manually'});
    const retried=(await snapshot()).tasks.find((t:any)=>t.id===renameId);
    assert.equal(retried.status,'running'); assert.equal(workers.length,beforeFailure+1);
    assert.equal(retried.events.filter((e:any)=>e.text==='pending history').length,1);
    workers.at(-1).emit('message',{type:'done',runId:retried.currentRunId,status:'completed'});
    // A missing patch must stop this run without replacing its durable context.
    const gapId=await invoke('task:submit',{projectId:project.id,prompt:'message protocol gap'});
    const gapTask=(await snapshot()).tasks.find((t:any)=>t.id===gapId), gapWorker=workers.at(-1);
    gapWorker.emit('message',{type:'message-patch',runId:gapTask.currentRunId,baseVersion:1,version:2,offset:0,remove:1,messages:[]});
    assert.ok(gapWorker.killed);
    const gapResult=(await snapshot()).tasks.find((t:any)=>t.id===gapId);
    assert.equal(gapResult.status,'failed');assert.match(gapResult.error,/同步顺序/);
    const gapDb=new DatabaseSync(path.join(userData,'local-code.sqlite'),{readOnly:true});
    const gapStored=JSON.parse(String(gapDb.prepare('SELECT data FROM tasks WHERE id=?').get(gapId)!.data));
    assert.equal(gapStored.messages.length,1);assert.equal(gapStored.messages[0].content,'message protocol gap');gapDb.close();

    // Per-chat overrides work even without a default and keep their own queued configuration.
    await invoke('settings:save',{...defaults,model:''});
    await assert.rejects(invoke('task:submit',{projectId:project.id,prompt:'no model'}),/选择模型/);
    await invoke('task:submit',{projectId:project.id,taskId:gapId,prompt:'continue with A',model:'model-a'});
    const modelAWorker=workers.at(-1);
    const modelBInput={projectId:project.id,prompt:'queued B',model:'model-b'};
    const modelBId=await invoke('task:submit',modelBInput);
    modelBInput.model='changed-after-submit';
    const queued=(await snapshot()).tasks.find((t:any)=>t.id===modelBId);
    assert.equal(queued.status,'queued');assert.equal(queued.model,'model-b');assert.equal(queued.runs[0].model,'model-b');
    assert.equal((await invoke('app:snapshot')).settings.model,'');
    await assert.rejects(invoke('settings:save',{...defaults,model:'other'}),/停止或完成/);
    await assert.rejects(invoke('task:submit',{projectId:project.id,taskId:gapId,prompt:'cannot replace active',model:'model-c'}),/尚未结束/);
    await new Promise(r=>setImmediate(r));
    const modelAStart=modelAWorker.sent.find((m:any)=>m.type==='start');
    assert.equal(modelAStart.input.model,'model-a');assert.equal(modelAStart.settings.model,'model-a');
    assert.ok(modelAStart.input.messages.some((m:any)=>m.content==='message protocol gap'),'switching models preserves earlier conversation');
    const modelATask=(await snapshot()).tasks.find((t:any)=>t.id===gapId);
    assert.equal(modelATask.runs[0].model,'mock');assert.equal(modelATask.runs.at(-1).model,'model-a');
    modelAWorker.emit('message',{type:'done',runId:modelATask.currentRunId,status:'completed'});
    await new Promise(r=>setImmediate(r));
    await new Promise(r=>setImmediate(r));
    const modelBWorker=workers.at(-1), modelBStart=modelBWorker.sent.find((m:any)=>m.type==='start');
    assert.equal(modelBStart.input.model,'model-b');assert.equal(modelBStart.settings.model,'model-b');
    modelBWorker.emit('message',{type:'done',runId:queued.currentRunId,status:'completed'});
    // Existing callers without an override continue to use the global default.
    await invoke('settings:save',{...defaults,model:'mock'});
    const legacyId=await invoke('task:submit',{projectId:project.id,taskId:gapId,prompt:'legacy caller'});
    const legacyTask=(await snapshot()).tasks.find((t:any)=>t.id===legacyId);
    assert.equal(legacyTask.model,'mock');assert.equal(legacyTask.runs.at(-1).model,'mock');
    const legacyWorker=workers.at(-1);await new Promise(r=>setImmediate(r));
    legacyWorker.emit('message',{type:'done',runId:legacyTask.currentRunId,status:'completed'});
  } finally { failWrites=false;Store.prototype.flush=originalFlush;Store.prototype.task=originalTask;Store.prototype.tasks=originalTasks;Store.prototype.detail=originalDetail;Module._load=original;app.emit('before-quit');await fs.rm(home,{recursive:true,force:true}); }
});
