const { contextBridge, ipcRenderer } = require('electron');
const subscribe = (channel, fn) => {
  const listener = (_event, value) => fn(value);
  ipcRenderer.on(channel, listener);
  return () => ipcRenderer.removeListener(channel, listener);
};
contextBridge.exposeInMainWorld('localCode', Object.freeze({
  loadSession: () => ipcRenderer.invoke('session:load'),
  saveView: view => ipcRenderer.invoke('session:save', view),
  flushView: view => ipcRenderer.sendSync('session:flush', view),
  startEvaluation: () => ipcRenderer.invoke('evaluation:start'),
  stopEvaluation: id => ipcRenderer.invoke('evaluation:stop', id),
  appInfo: () => ipcRenderer.invoke('app:info'),
  openDataDirectory: () => ipcRenderer.invoke('app:open-data'),
  exportDiagnostics: () => ipcRenderer.invoke('app:export-diagnostics'),
  openLink: url => ipcRenderer.invoke('app:open-link', url),
  copyText: text => ipcRenderer.invoke('app:copy-text', text),
  snapshot: () => ipcRenderer.invoke('app:snapshot'),
  addProject: () => ipcRenderer.invoke('project:add'),
  removeProject: projectId => ipcRenderer.invoke('project:remove', projectId),
  renameTask: (taskId, title) => ipcRenderer.invoke('task:rename', { taskId, title }),
  archiveTask: (taskId, archived) => ipcRenderer.invoke('task:archive', { taskId, archived }),
  taskEvents: input => ipcRenderer.invoke('task:events', input),
  taskDetail: taskId => ipcRenderer.invoke('task:detail', taskId),
  taskSummary: taskId => ipcRenderer.invoke('task:summary', taskId),
  taskPage: input => ipcRenderer.invoke('tasks:page', input),
  searchTasks: input => ipcRenderer.invoke('tasks:search', input),
  planText: (taskId, runId) => ipcRenderer.invoke('runs:plan', { taskId, runId }),
  changePatch: input => ipcRenderer.invoke('changes:patch', input),
  saveSettings: settings => ipcRenderer.invoke('settings:save', settings),
  models: () => ipcRenderer.invoke('models:list'),
  loadModel: key => ipcRenderer.invoke('models:load', key),
  unloadModel: id => ipcRenderer.invoke('models:unload', id),
  searchFiles: input => ipcRenderer.invoke('files:search', input),
  listDirectory: input => ipcRenderer.invoke('files:list', input),
  previewFile: input => ipcRenderer.invoke('files:preview', input),
  referenceFile: input => ipcRenderer.invoke('files:reference', input),
  runChanges: (taskId, runId) => ipcRenderer.invoke('runs:changes', { taskId, runId }),
  previewRollback: (taskId, runId, path) => ipcRenderer.invoke('rollback:preview', { taskId, runId, path }),
  confirmRollback: token => ipcRenderer.invoke('rollback:confirm', token),
  submit: input => ipcRenderer.invoke('task:submit', input),
  stop: id => ipcRenderer.invoke('task:stop', id),
  approve: (taskId, approvalId, allow) => ipcRenderer.invoke('task:approve', { taskId, approvalId, allow }),
  onUpdate: fn => subscribe('app:update', fn),
  onDelta: fn => subscribe('task:delta', fn),
}));
